[workspace]
resolver = "2"
members = [
  "crates/*",
  "apps/*/src-tauri",
]

[workspace.package]
version = "0.1.2"
edition = "2021"
rust-version = "1.85"
license = "MIT"

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
