//! Numerical parity of the Rust SECS port against the Python reference.
//!
//! The reference is SECS by 한플 (Hanpeul), published on the DCInside speaker
//! gallery:
//! <https://gall.dcinside.com/mgallery/board/view/?id=speakers&no=514096&s_type=search_name&s_keyword=%ED%95%9C%ED%94%8C&page=1>
//! Ported and compared here with the original author's permission; see
//! `THIRD-PARTY-NOTICES.md`.
//!
//! `testdata/secs-parity.json` is generated by running the extracted SECS.py
//! DSP core (scratchpad harness, see HANDOFF) on a synthetic stereo impulse
//! response that this test rebuilds from the same analytic formula: deltas,
//! exponentially decaying modes, and RBJ Butterworth biquads, all f64.
//!
//! SECS.py computes long stretches in float32 while the port uses f64, so the
//! comparisons are tolerance-based, not bit-exact. Discrete decisions (peak
//! indices, the chosen automatic delay) must still match exactly.

use eqforbeginner_dsp_core::secs::{
    design_secs_stereo_filter, secs_resample_poly, SecsConfig, SecsResolutionMode,
};
use rustfft::num_complex::Complex;
use rustfft::FftPlanner;
use serde_json::Value;

const FIXTURE: &str = include_str!("../../../testdata/secs-parity.json");
const SAMPLE_RATE: f64 = 48_000.0;
const BUTTERWORTH_Q: f64 = std::f64::consts::FRAC_1_SQRT_2;

fn biquad(signal: &[f64], b0: f64, b1: f64, b2: f64, a1: f64, a2: f64) -> Vec<f64> {
    let mut output = vec![0.0; signal.len()];
    let (mut x1, mut x2, mut y1, mut y2) = (0.0, 0.0, 0.0, 0.0);
    for (slot, sample) in output.iter_mut().zip(signal.iter()) {
        let x0 = *sample;
        let y0 = b0 * x0 + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2;
        *slot = y0;
        x2 = x1;
        x1 = x0;
        y2 = y1;
        y1 = y0;
    }
    output
}

fn biquad_highpass(signal: &[f64], corner_hz: f64) -> Vec<f64> {
    let w0 = 2.0 * std::f64::consts::PI * corner_hz / SAMPLE_RATE;
    let cos_w0 = w0.cos();
    let alpha = w0.sin() / (2.0 * BUTTERWORTH_Q);
    let a0 = 1.0 + alpha;
    biquad(
        signal,
        (1.0 + cos_w0) / 2.0 / a0,
        -(1.0 + cos_w0) / a0,
        (1.0 + cos_w0) / 2.0 / a0,
        -2.0 * cos_w0 / a0,
        (1.0 - alpha) / a0,
    )
}

fn biquad_lowpass(signal: &[f64], corner_hz: f64) -> Vec<f64> {
    let w0 = 2.0 * std::f64::consts::PI * corner_hz / SAMPLE_RATE;
    let cos_w0 = w0.cos();
    let alpha = w0.sin() / (2.0 * BUTTERWORTH_Q);
    let a0 = 1.0 + alpha;
    biquad(
        signal,
        (1.0 - cos_w0) / 2.0 / a0,
        (1.0 - cos_w0) / a0,
        (1.0 - cos_w0) / 2.0 / a0,
        -2.0 * cos_w0 / a0,
        (1.0 - alpha) / a0,
    )
}

#[allow(clippy::too_many_arguments)]
fn synth_channel(
    length: usize,
    direct_index: usize,
    direct_amplitude: f64,
    reflections: &[(usize, f64)],
    modes: &[(f64, f64, f64, f64)],
    highpass_hz: f64,
    lowpass_hz: f64,
    post_gain: f64,
) -> Vec<f64> {
    let mut signal = vec![0.0; length];
    signal[direct_index] = direct_amplitude;
    for (offset, amplitude) in reflections {
        signal[direct_index + offset] += amplitude;
    }
    for offset in 0..length - direct_index {
        let time = offset as f64 / SAMPLE_RATE;
        for (frequency, amplitude, tau, phase) in modes {
            signal[direct_index + offset] += amplitude
                * (-time / tau).exp()
                * (2.0 * std::f64::consts::PI * frequency * time + phase).sin();
        }
    }
    let signal = biquad_highpass(&signal, highpass_hz);
    let signal = biquad_lowpass(&signal, lowpass_hz);
    let signal = biquad_lowpass(&signal, lowpass_hz);
    signal.iter().map(|sample| sample * post_gain).collect()
}

fn synth_ir(length: usize) -> (Vec<f64>, Vec<f64>) {
    let left = synth_channel(
        length,
        100,
        1.0,
        &[(143, 0.55), (331, -0.4), (557, 0.3)],
        &[
            (46.7, 8.3e-4, 0.25, 0.0),
            (71.3, -1.16e-3, 0.09, 1.1),
            (113.0, 1.39e-3, 0.06, 2.3),
        ],
        52.0,
        13_000.0,
        1.0,
    );
    let right = synth_channel(
        length,
        112,
        0.92,
        &[(161, 0.5), (389, -0.35)],
        &[
            (44.1, 8.5e-4, 0.22, 0.7),
            (76.5, -1.15e-3, 0.08, 0.0),
            (108.0, 1.5e-3, 0.055, 1.9),
        ],
        58.0,
        12_800.0,
        0.9,
    );
    (left, right)
}

fn as_f64(value: &Value) -> f64 {
    value.as_f64().expect("fixture value must be a number")
}

fn as_f64_vec(value: &Value) -> Vec<f64> {
    value
        .as_array()
        .expect("fixture value must be an array")
        .iter()
        .map(as_f64)
        .collect()
}

fn fft_real(samples: &[f64], fft_size: usize) -> Vec<Complex<f64>> {
    let mut buffer = vec![Complex::new(0.0, 0.0); fft_size];
    for (slot, sample) in buffer.iter_mut().zip(samples.iter()) {
        slot.re = *sample;
    }
    FftPlanner::<f64>::new()
        .plan_fft_forward(fft_size)
        .process(&mut buffer);
    buffer
}

fn interp_clamped(x: f64, xs: &[f64], ys: &[f64]) -> f64 {
    if x <= xs[0] {
        return ys[0];
    }
    if x >= xs[xs.len() - 1] {
        return ys[ys.len() - 1];
    }
    let upper = xs.partition_point(|value| *value < x).max(1);
    let lower = upper - 1;
    let span = xs[upper] - xs[lower];
    if span <= 0.0 {
        return ys[lower];
    }
    ys[lower] + (ys[upper] - ys[lower]) * (x - xs[lower]) / span
}

struct CurveCheck<'a> {
    name: &'a str,
    expected: Vec<f64>,
    actual: Vec<f64>,
    max_abs_db: f64,
    mean_abs_db: f64,
}

impl CurveCheck<'_> {
    fn assert(&self) {
        assert_eq!(self.expected.len(), self.actual.len(), "{}", self.name);
        let mut worst = 0.0f64;
        let mut total = 0.0f64;
        for (expected, actual) in self.expected.iter().zip(self.actual.iter()) {
            let difference = (expected - actual).abs();
            worst = worst.max(difference);
            total += difference;
        }
        let mean = total / self.expected.len() as f64;
        assert!(
            worst <= self.max_abs_db,
            "{}: worst dB difference {worst} exceeds {}",
            self.name,
            self.max_abs_db
        );
        assert!(
            mean <= self.mean_abs_db,
            "{}: mean dB difference {mean} exceeds {}",
            self.name,
            self.mean_abs_db
        );
    }
}

fn relative_close(name: &str, expected: f64, actual: f64, tolerance: f64) {
    let scale = expected.abs().max(1e-12);
    assert!(
        ((expected - actual) / scale).abs() <= tolerance,
        "{name}: expected {expected}, got {actual} (relative tolerance {tolerance})"
    );
}

fn absolute_close(name: &str, expected: f64, actual: f64, tolerance: f64) {
    assert!(
        (expected - actual).abs() <= tolerance,
        "{name}: expected {expected}, got {actual} (absolute tolerance {tolerance})"
    );
}

fn config_from_fixture(config: &Value) -> SecsConfig {
    let resolution = match config["res_mode"].as_i64().unwrap() {
        0 => SecsResolutionMode::Gentle,
        1 => SecsResolutionMode::Balanced,
        _ => SecsResolutionMode::Precise,
    };
    SecsConfig {
        sample_rate_hz: config["target_sr"].as_u64().unwrap() as u32,
        max_boost_db: as_f64(&config["max_boost"]),
        target_delay_ms: as_f64(&config["target_delay"]),
        tilt_db_per_octave: as_f64(&config["tilt_db_oct"]),
        bass_boost_db: as_f64(&config["bass_boost_db"]),
        bass_frequency_hz: as_f64(&config["bass_freq"]),
        resolution,
        taps: config["taps"].as_u64().unwrap() as usize,
        hf_min_phase_reference_hz: as_f64(&config["hf_min_phase_ref_hz"]),
        low_latency: config["low_latency"].as_bool().unwrap(),
        zero_latency: config["zero_latency"].as_bool().unwrap(),
        // SECS.py has no house-curve overlay and no shared-sub-band
        // commonization; parity pins the plain path.
        target_overlay: None,
        shared_low_frequency_hz: None,
    }
}

fn taps_check(name: &str, expected: &[f64], actual: &[f64]) {
    assert_eq!(expected.len(), actual.len(), "{name}: length");
    let peak = expected
        .iter()
        .map(|tap| tap.abs())
        .fold(f64::NEG_INFINITY, f64::max)
        .max(1e-9);
    let mut worst = 0.0f64;
    let mut sum_squares = 0.0f64;
    for (expected_tap, actual_tap) in expected.iter().zip(actual.iter()) {
        let difference = (expected_tap - actual_tap).abs();
        worst = worst.max(difference);
        sum_squares += difference * difference;
    }
    let rms = (sum_squares / expected.len() as f64).sqrt();
    assert!(
        worst <= 5e-4 * peak,
        "{name}: worst tap difference {worst} vs peak {peak}"
    );
    assert!(
        rms <= 1e-4 * peak,
        "{name}: rms tap difference {rms} vs peak {peak}"
    );
}

#[test]
fn the_rust_port_matches_the_python_reference() {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("fixture parses");
    assert_eq!(fixture["schema"], "eqforbeginner-secs-parity-v1");
    let length = fixture["ir_length"].as_u64().unwrap() as usize;
    let (left_ir, right_ir) = synth_ir(length);

    // The fixture stores checksums of the Python-generated IR; the analytic
    // formula must reproduce it to ~1e-9 relative before any DSP comparison
    // is meaningful.
    let checks = &fixture["ir_checksums"];
    relative_close(
        "left_sum_sq",
        as_f64(&checks["left_sum_sq"]),
        left_ir.iter().map(|v| v * v).sum::<f64>(),
        1e-9,
    );
    relative_close(
        "right_sum_sq",
        as_f64(&checks["right_sum_sq"]),
        right_ir.iter().map(|v| v * v).sum::<f64>(),
        1e-9,
    );
    relative_close(
        "left_abs_sum",
        as_f64(&checks["left_abs_sum"]),
        left_ir.iter().map(|v| v.abs()).sum::<f64>(),
        1e-9,
    );
    relative_close(
        "right_abs_sum",
        as_f64(&checks["right_abs_sum"]),
        right_ir.iter().map(|v| v.abs()).sum::<f64>(),
        1e-9,
    );

    // scipy resample_poly parity: the (a)-mode export resamples the P0 IR to
    // each native rate with this function before re-running the design, so
    // the port must match scipy sample for sample, not merely in spectrum.
    for case in fixture["resample_cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let up = case["up"].as_u64().unwrap() as u32;
        let down = case["down"].as_u64().unwrap() as u32;
        let resampled = secs_resample_poly(&left_ir, up, down).expect("resample succeeds");
        assert_eq!(
            resampled.len(),
            case["length"].as_u64().unwrap() as usize,
            "{name}: output length"
        );
        relative_close(
            &format!("{name}: sum_sq"),
            as_f64(&case["sum_sq"]),
            resampled.iter().map(|v| v * v).sum::<f64>(),
            1e-9,
        );
        relative_close(
            &format!("{name}: abs_sum"),
            as_f64(&case["abs_sum"]),
            resampled.iter().map(|v| v.abs()).sum::<f64>(),
            1e-9,
        );
        for (label, expected, start) in [
            ("head", as_f64_vec(&case["head"]), 0usize),
            (
                "mid",
                as_f64_vec(&case["mid"]),
                case["mid_start"].as_u64().unwrap() as usize,
            ),
        ] {
            for (offset, expected_sample) in expected.iter().enumerate() {
                absolute_close(
                    &format!("{name}: {label} sample {offset}"),
                    *expected_sample,
                    resampled[start + offset],
                    1e-10,
                );
            }
        }
    }

    let query = as_f64_vec(&fixture["query_frequencies_hz"]);

    for case in fixture["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let config = config_from_fixture(&case["config"]);
        let expected = &case["expected"];
        let design = design_secs_stereo_filter(&left_ir, &right_ir, &config, None, None)
            .expect("design succeeds");

        let expected_peaks = as_f64_vec(&expected["peaks"]);
        assert_eq!(
            design.channels[0].peak_index, expected_peaks[0] as usize,
            "{name}: left peak index"
        );
        assert_eq!(
            design.channels[1].peak_index, expected_peaks[1] as usize,
            "{name}: right peak index"
        );
        absolute_close(
            &format!("{name}: auto_delay_ms"),
            as_f64(&expected["auto_delay_ms"]),
            design.auto_delay_ms,
            0.0,
        );
        relative_close(
            &format!("{name}: low_cutoff_hz"),
            as_f64(&expected["low_cutoff_hz"]),
            design.low_cutoff_hz,
            1e-6,
        );
        relative_close(
            &format!("{name}: high_cutoff_hz"),
            as_f64(&expected["high_cutoff_hz"]),
            design.high_cutoff_hz,
            1e-6,
        );
        relative_close(
            &format!("{name}: rms_scale"),
            as_f64(&expected["rms_scale"]),
            design.rms_scale,
            1e-9,
        );
        absolute_close(
            &format!("{name}: preamp_db"),
            as_f64(&expected["preamp_db"]),
            design.preamp_db,
            1e-3,
        );
        absolute_close(
            &format!("{name}: lr_offset_db"),
            as_f64(&expected["lr_offset_db"]),
            design.channel_balance_trim_db,
            1e-3,
        );

        if let Some(metrics) = expected.get("stage1_metrics") {
            let metrics = metrics.as_array().unwrap();
            assert_eq!(
                metrics.len(),
                design.delay_metrics.len(),
                "{name}: metric count"
            );
            for (index, (expected_metric, actual_metric)) in
                metrics.iter().zip(design.delay_metrics.iter()).enumerate()
            {
                match (expected_metric.as_f64(), actual_metric) {
                    (Some(expected_value), Some(actual_value)) => absolute_close(
                        &format!("{name}: stage1 metric {index}"),
                        expected_value,
                        *actual_value,
                        2e-3,
                    ),
                    (None, None) => {}
                    (expected_value, actual_value) => panic!(
                        "{name}: stage1 metric {index} mismatch: {expected_value:?} vs {actual_value:?}"
                    ),
                }
            }
        }
        if let Some(channel_lows) = expected.get("channel_low_cutoffs") {
            let lows = as_f64_vec(channel_lows);
            let highs = as_f64_vec(&expected["channel_high_cutoffs"]);
            let refs = as_f64_vec(&expected["channel_ref_mags"]);
            for channel in 0..2 {
                relative_close(
                    &format!("{name}: channel {channel} low cutoff"),
                    lows[channel],
                    design.channels[channel].low_cutoff_hz,
                    1e-6,
                );
                relative_close(
                    &format!("{name}: channel {channel} high cutoff"),
                    highs[channel],
                    design.channels[channel].high_cutoff_hz,
                    1e-6,
                );
                relative_close(
                    &format!("{name}: channel {channel} ref mag"),
                    refs[channel],
                    design.channels[channel].reference_magnitude,
                    1e-4,
                );
            }
        }

        // Reproduce the fixture's evaluation curves from the designed taps.
        let fft_len = length.max(config.taps);
        let sample_rate = f64::from(config.sample_rate_hz);
        let bin_hz = sample_rate / fft_len as f64;
        let eval_bins: Vec<usize> = (1..fft_len / 2 + 1)
            .filter(|index| {
                let frequency = *index as f64 * bin_hz;
                frequency > 10.0 && frequency < sample_rate / 2.0
            })
            .collect();
        let f_eval: Vec<f64> = eval_bins
            .iter()
            .map(|index| *index as f64 * bin_hz)
            .collect();
        let h_ir = [fft_real(&left_ir, fft_len), fft_real(&right_ir, fft_len)];
        let h_fil = [
            fft_real(&design.left_taps, fft_len),
            fft_real(&design.right_taps, fft_len),
        ];
        let shift_amount = |channel: usize| -> f64 {
            if config.zero_latency {
                design.channels[channel].peak_index as f64
            } else {
                let delay_samples = ((design.auto_delay_ms / 1000.0) * sample_rate) as usize;
                (design.channels[0]
                    .peak_index
                    .max(design.channels[1].peak_index)
                    + delay_samples) as f64
            }
        };
        for (channel, channel_name) in [(0usize, "left"), (1usize, "right")] {
            let shift = shift_amount(channel);
            let filter_db: Vec<f64> = eval_bins
                .iter()
                .map(|index| 20.0 * (h_fil[channel][*index].norm() + 1e-12).log10())
                .collect();
            let system_db: Vec<f64> = eval_bins
                .iter()
                .map(|index| {
                    let frequency = *index as f64 * bin_hz;
                    let rotation = Complex::from_polar(
                        1.0,
                        2.0 * std::f64::consts::PI * frequency * shift / sample_rate,
                    );
                    let system = h_ir[channel][*index] * h_fil[channel][*index] * rotation;
                    20.0 * (system.norm() + 1e-12).log10()
                })
                .collect();
            CurveCheck {
                name: &format!("{name}: filter curve {channel_name}"),
                expected: as_f64_vec(&expected[&format!("filter_db_{channel_name}")]),
                actual: query
                    .iter()
                    .map(|f| interp_clamped(*f, &f_eval, &filter_db))
                    .collect(),
                max_abs_db: 0.3,
                mean_abs_db: 0.01,
            }
            .assert();
            CurveCheck {
                name: &format!("{name}: system curve {channel_name}"),
                expected: as_f64_vec(&expected[&format!("system_db_{channel_name}")]),
                actual: query
                    .iter()
                    .map(|f| interp_clamped(*f, &f_eval, &system_db))
                    .collect(),
                max_abs_db: 0.3,
                mean_abs_db: 0.01,
            }
            .assert();
        }

        let target_db: Vec<f64> = query
            .iter()
            .map(|f| {
                20.0 * (interp_clamped(*f, &design.target_frequencies_hz, &design.target_magnitude)
                    + 1e-12)
                    .log10()
            })
            .collect();
        CurveCheck {
            name: &format!("{name}: target curve"),
            expected: as_f64_vec(&expected["target_db"]),
            actual: target_db,
            max_abs_db: 5e-3,
            mean_abs_db: 1e-3,
        }
        .assert();

        for (channel_name, taps) in [("left", &design.left_taps), ("right", &design.right_taps)] {
            let head = as_f64_vec(&expected[&format!("{channel_name}_head")]);
            taps_check(
                &format!("{name}: {channel_name} head taps"),
                &head,
                &taps[..head.len()],
            );
            let peak_start = expected[&format!("{channel_name}_peak_start")]
                .as_u64()
                .unwrap() as usize;
            let peak_segment = as_f64_vec(&expected[&format!("{channel_name}_peak")]);
            taps_check(
                &format!("{name}: {channel_name} peak taps"),
                &peak_segment,
                &taps[peak_start..peak_start + peak_segment.len()],
            );
            relative_close(
                &format!("{name}: {channel_name} abs sum"),
                as_f64(&expected[&format!("{channel_name}_abs_sum")]),
                taps.iter().map(|tap| tap.abs()).sum::<f64>(),
                1e-3,
            );
            let expected_peak_index = expected[&format!("{channel_name}_peak_index")]
                .as_u64()
                .unwrap() as usize;
            let mut actual_peak_index = 0;
            let mut actual_peak_value = f64::NEG_INFINITY;
            for (index, tap) in taps.iter().enumerate() {
                if tap.abs() > actual_peak_value {
                    actual_peak_value = tap.abs();
                    actual_peak_index = index;
                }
            }
            assert_eq!(
                actual_peak_index, expected_peak_index,
                "{name}: {channel_name} filter peak index"
            );
        }
    }
}
